export default {
  parts: ['productPrice', 'productPriceRow', 'comparablePrice', 'oldPrice', 'discount'],
  baseStyle: () => ({
    productPriceWrapper: {
      flexDirection: 'column',
      gap: 'var(--spacing-2)',
    },
    productPrice: {
      fontFamily: 'var(--font-face1-normal)',
      color: 'var(--neutrals-grey-900, #161616)',
      fontSize: 'var(--text-16)',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '125%',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    productPriceRow: {
      gap: '3px',
      flexWrap: 'nowrap',
    },
    comparablePrice: {
      color: 'var(--neutrals-grey-600, #6D6D6D)',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-12)',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '125%',
      letterSpacing: 'var(--letter-spacing-xs)',
      whiteSpace: 'nowrap',
      display: 'flex',
      alignItems: 'center',
    },
    oldPrice: {
      color: 'var(--neutrals-grey-600, #6D6D6D)',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-16)',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '125%',
      letterSpacing: 'var(--letter-spacing-xs)',
      textDecoration: 'line-through',
    },
    discount: {
      color: 'var(--color-success-primary, #427E2B)',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-16)',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '125%',
      letterSpacing: 'var(--letter-spacing-xs)',
      whiteSpace: 'nowrap',
    },
  }),
}
