export default {
  baseStyle: ({ theme }) => ({
    container: {
      bg: 'var(--color-neutral-light-1)',
      pt: 'var(--spacing-8)',
      pb: 'var(--spacing-10)',
      w: '100%',
    },
    inner: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--spacing-4)',
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      px: 'var(--spacing-3)',
      gap: 'var(--spacing-2)',
    },
    thumbnail: {
      w: '44px',
      aspectRatio: '1 / 1',
      borderRadius: '50%',
      overflow: 'hidden',
      flexShrink: 0,
      bg: 'var(--color-neutral-light-2)',
      '& img': {
        w: '100%',
        h: '100%',
        objectFit: 'cover',
      },
    },
    titleWrapper: {
      display: 'flex',
      flexDirection: 'column',
      gap: '6px',
    },
    eyebrow: {
      ...theme.typography['text-title1-s'],
      color: 'var(--color-neutral-medium)',
    },
    productName: {
      ...theme.typography['text-display4-xxs'],
      color: 'var(--color-black-base)',
    },
    carouselTrack: {
      display: 'flex',
      gap: 'var(--spacing-1)',
      pl: 'var(--spacing-3)',
      overflowX: 'auto',
      overflowY: 'hidden',
      '&::-webkit-scrollbar': { display: 'none' },
      msOverflowStyle: 'none',
      scrollbarWidth: 'none',
    },
    card: {
      w: '144px',
      flexShrink: 0,
      bg: 'var(--color-neutral-light-1)',
      pb: 'var(--spacing-4)',
      display: 'flex',
      flexDirection: 'column',
    },
    cardImageWrapper: {
      aspectRatio: '4 / 5',
      bg: 'var(--color-neutral-light-1)',
      overflow: 'hidden',
    },
    cardImage: {
      w: '100%',
      h: '100%',
      maxW: 'none',
      objectFit: 'cover',
    },
    cardNamePriceWrapper: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--spacing-1)',
      px: 'var(--spacing-3)',
      mt: 'var(--spacing-2)',
    },
    cardName: {
      ...theme.typography['text-title2-s'],
      textAlign: 'center',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      color: 'var(--color-black-base)',
    },
    cardAtbWrapper: {
      px: '10px',
    },
    atbButton: {
      ...theme.typography['text-cta2-xs'],
      h: 'var(--spacing-10)',
      w: '100%',
      minW: '110px',
      borderRadius: '130px',
      border: '1px solid var(--color-neutral-light-2)',
      bg: 'var(--color-white-base)',
      color: 'var(--color-black-base)',
      _hover: { bg: 'var(--color-neutral-light-2)' },
    },
    skeletonCarousel: {
      display: 'flex',
      gap: 'var(--spacing-1)',
      pl: 'var(--spacing-3)',
      overflowX: 'hidden',
    },
    skeletonCard: {
      w: '144px',
      flexShrink: 0,
    },
    skeletonCardImage: {
      aspectRatio: '4 / 5',
      w: '100%',
    },
    skeletonCardName: {
      h: '14px',
      w: '80%',
      mt: 'var(--spacing-2)',
      mx: 'var(--spacing-3)',
    },
    skeletonCardPrice: {
      h: '14px',
      w: '60%',
      mt: 'var(--spacing-1)',
      mx: 'var(--spacing-3)',
    },
  }),
}
