import { IPHONE_PRO_MAX_SCREEN_WIDTH } from 'toro/constants/adaptiveExperience'

export default {
  baseStyle: ({ theme }) => ({
    accessorizeItContainerRoot: {
      backgroundColor: 'var(--color-page-bg, #F0F0F0)',
      padding: 'var(--spacing-10) var(--spacing-3) var(--spacing-6)',
    },
    accessorizeItContainerWrapper: {
      borderRadius: 'unset',
      boxShadow: 'none',
      backdropFilter: 'none',
      padding: '0',
    },
    accessorizeItTitle: {
      ...theme.typography['text-display4-s'],
      fontFamily: 'var(--font-face1-extended-bold)',
      color: 'var(--color-black-base)',
      textAlign: 'center',
      fontSize: 'var(--text-24)',
      lineHeight: 'var(--line-height-100)',
      letterSpacing: 'var(--letter-spacing-s)',
      marginBottom: '5px',
    },
    accessorizeItSubtitle: {
      ...theme.typography['text-cta2-s'],
      fontFamily: 'var(--font-face1-extended-normal)',
      color: 'var(--neutrals-grey-900, #161616)',
      textAlign: 'center',
      fontWeight: 400,
      fontSize: 'var(--text-14)',
      lineHeight: 'var(--line-height-100)',
      letterSpacing: 'var(--letter-spacing-xs)',
      padding: '0',
      marginTop: '2px',
    },
    accessorizeItContanerTabsWrapper: {
      background: 'transparent',
      borderRadius: 'unset',
      border: 'none',
      mask: 'none',
      padding: '0',
    },
    accessorizeItTabList: {
      display: 'flex',
      padding: '3px',
      alignItems: 'center',
      alignSelf: 'stretch',
      borderRadius: '10px',
      background: 'var(--Neutrals-color-neutral-light-2, #E1E1E1)',
      border: 'none',
      w: '100%',
    },
    accessorizeItTabPanels: {
      '& .scrollable-container-with-arrows': {
        justifyContent: 'space-between',
        '& .scrollable-container': {
          width: '266px',
          justifyContent: 'center',
          [`@media (min-width: ${IPHONE_PRO_MAX_SCREEN_WIDTH}px)`]: {
            width: '332px',
          },
        },
      },
    },
    accessorizeItTab: {
      ...theme.typography['text-cta2-s'],
      display: 'flex',
      height: '48px',
      padding: '18px 22px',
      justifyContent: 'center',
      alignItems: 'center',
      flex: '1 0 0',
      borderRadius: 'var(--spacing-2)',
      background: 'transparent',
      border: 'none',
      mb: '0',
      w: '100%',
      '&.active-tab': {
        background: 'var(--color-white-base)',
        boxShadow: '0 4px 14px 0 rgba(0, 0, 0, 0.05)',
        color: 'var(--color-black-base)',
      },
    },
    accessorizeItPriceLabel: {
      ...theme.typography['text-title1-m'],
      fontFamily: 'var(--font-face1-extended-normal)',
      color: 'var(--color-black-base)',
      textAlign: 'center',
      fontWeight: 400,
      fontSize: 'var(--text-14)',
      lineHeight: '125%',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    accessorizeItPrice: {
      fontWeight: 400,
    },
    accessorizeItImageContainer: {
      height: '416.253px',
      aspectRatio: '406.00/416.25',
      borderRadius: 'var(--border-radius-l)',
      margin: '0',
    },
    accessorizeItTabs: {
      gap: '0px',
    },
    accessorizeItTabPanel: {
      marginBottom: '23px',
      marginTop: '10px',
    },
    accessorizeItProduct: {
      h: 'auto',
      minWidth: '64px',
      '& img': {
        w: '64px',
        height: 'auto',
        maxHeight: '76px',
      },
    },
    accessorizeItATBButtonsContainer: {
      gap: 'var(--spacing-1)',
    },
    accessorizeItATBButton: {
      display: 'flex',
      height: '58px',
      padding: 'var(--spacing-6) var(--spacing-10) var(--spacing-5) var(--spacing-10)',
      justifyContent: 'center',
      alignItems: 'center',
      flex: '1 0 0',
      borderRadius: 'var(--spacing-2)',
      border: 'none',
      '& svg': {
        display: 'none',
      },
      '&:hover': {
        backgroundColor: 'var(--color-black-base) !important',
      },
      '&:active': {
        backgroundColor: 'var(--color-black-base) !important',
      },
    },
    accessorizeItATBBundleButton: {
      display: 'flex',
      height: '58px',
      padding: 'var(--spacing-6) var(--spacing-10) var(--spacing-5) var(--spacing-10)',
      justifyContent: 'center',
      alignItems: 'center',
      flex: '1 0 0',
      borderRadius: 'var(--spacing-2)',
      border: 'none',
      '& svg': {
        display: 'none',
      },
    },
    accessorizeItButtonWrapper: {
      position: 'absolute',
      top: 'unset',
      bottom: 'var(--spacing-3)',
      right: 'var(--spacing-4)',
      zIndex: 10,
      h: '40px',
      w: '165px',
    },
    accessorizeItButton: {
      position: 'relative',
      padding: 'var(--spacing-3) var(--spacing-6) var(--spacing-3) var(--spacing-6)',
      background: 'var(--color-white-base)',
      border: '1.4px solid transparent',
      borderRadius: 'var(--border-radius-full)',
      backgroundClip: 'padding-box',
      height: '40px',
      '&:before': {
        content: '""',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: -1,
        margin: '-1.4px',
        borderRadius: 'inherit',
      },
      '&:hover:not(:disabled)': {
        backgroundColor: 'var(--color-white-base)',
      },
    },
    rootSkeleton: {
      padding: 'var(--spacing-10) var(--spacing-3) var(--spacing-6)',
    },
  }),
}
