const mobileStyles = {
  '& .product-tile:nth-of-type(2n + 1):has(+ .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(2n + 1):has(.comparablePrice .comparablePriceWrapper)+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper))':
    {
      height: 'var(--staircase-comparablePrice-height)',
    },
  '& .product-tile:nth-of-type(2n + 1):has(+ .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(2n + 1):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper))':
    {
      height: 'var(--staircase-promoCallout-height)',
    },
  '& .product-tile:nth-of-type(2n + 1):has(+ .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(2n + 1):has(.product-tile-atb-area .atb-content)+.product-tile .product-tile-atb-area:not(:has(.atb-content))':
    {
      height: 'var(--staircase-addToBag-height)',
    },
  '& .product-tile:nth-of-type(2n + 1):has(+ .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(2n + 1):has(.product-tile-vs-area .vs-content)+.product-tile .product-tile-vs-area:not(:has(.vs-content))':
    {
      height: 'var(--staircase-viewSimilar-height)',
    },
  '& .product-tile:nth-of-type(2n + 1):has(+ .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(2n + 1):has(.product-tile-review-area .review-content)+.product-tile .product-tile-review-area:not(:has(.review-content))':
    {
      height: 'var(--staircase-reviews-height)',
    },
}

const desktopStyles = {
  '& .product-tile:nth-of-type(4n + 1):has(+ .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 1):has(+ div + .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 1):has(+ div + div + .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 1):has(.comparablePrice .comparablePriceWrapper)+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 2):has(+ .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 2):has(+ div + .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 1):has(.comparablePrice .comparablePriceWrapper)+div+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 2):has(.comparablePrice .comparablePriceWrapper)+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 3):has(+ .product-tile .comparablePrice .comparablePriceWrapper) .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 1):has(.comparablePrice .comparablePriceWrapper)+div+div+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 2):has(.comparablePrice .comparablePriceWrapper)+div+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper)), & .product-tile:nth-of-type(4n + 3):has(.comparablePrice .comparablePriceWrapper)+.product-tile .comparablePrice:not(:has(.comparablePriceWrapper))':
    {
      height: 'var(--staircase-comparablePrice-height)',
    },
  '& .product-tile:nth-of-type(4n + 1):has(+ .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 1):has(+ div + .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 1):has(+ div + div + .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 1):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 2):has(+ .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 2):has(+ div + .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 1):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+div+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 2):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 3):has(+ .product-tile .tilePromoCalloutWrapper .promoCalloutWrapper) .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 1):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+div+div+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 2):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+div+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper)), & .product-tile:nth-of-type(4n + 3):has(.tilePromoCalloutWrapper .promoCalloutWrapper)+.product-tile .tilePromoCalloutWrapper:not(:has(.promoCalloutWrapper))':
    {
      height: 'var(--staircase-promoCallout-height)',
    },
  '& .product-tile:nth-of-type(4n + 1):has(+ .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 1):has(+ div + .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 1):has(+ div + div + .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-atb-area .atb-content)+.product-tile .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 2):has(+ .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 2):has(+ div + .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-atb-area .atb-content)+div+.product-tile .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 2):has(.product-tile-atb-area .atb-content)+.product-tile .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 3):has(+ .product-tile .product-tile-atb-area .atb-content) .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-atb-area .atb-content)+div+div+.product-tile .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 2):has(.product-tile-atb-area .atb-content)+div+.product-tile .product-tile-atb-area:not(:has(.atb-content)), & .product-tile:nth-of-type(4n + 3):has(.product-tile-atb-area .atb-content)+.product-tile .product-tile-atb-area:not(:has(.atb-content))':
    {
      height: 'var(--staircase-addToBag-height)',
    },
  '& .product-tile:nth-of-type(4n + 1):has(+ .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 1):has(+ div + .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 1):has(+ div + div + .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-vs-area .vs-content)+.product-tile .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 2):has(+ .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 2):has(+ div + .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-vs-area .vs-content)+div+.product-tile .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 2):has(.product-tile-vs-area .vs-content)+.product-tile .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 3):has(+ .product-tile .product-tile-vs-area .vs-content) .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-vs-area .vs-content)+div+div+.product-tile .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 2):has(.product-tile-vs-area .vs-content)+div+.product-tile .product-tile-vs-area:not(:has(.vs-content)), & .product-tile:nth-of-type(4n + 3):has(.product-tile-vs-area .vs-content)+.product-tile .product-tile-vs-area:not(:has(.vs-content))':
    {
      height: 'var(--staircase-viewSimilar-height)',
    },
  '& .product-tile:nth-of-type(4n + 1):has(+ .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 1):has(+ div + .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 1):has(+ div + div + .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-review-area .review-content)+.product-tile .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 2):has(+ .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 2):has(+ div + .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-review-area .review-content)+div+.product-tile .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 2):has(.product-tile-review-area .review-content)+.product-tile .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 3):has(+ .product-tile .product-tile-review-area .review-content) .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 1):has(.product-tile-review-area .review-content)+div+div+.product-tile .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 2):has(.product-tile-review-area .review-content)+div+.product-tile .product-tile-review-area:not(:has(.review-content)), & .product-tile:nth-of-type(4n + 3):has(.product-tile-review-area .review-content)+.product-tile .product-tile-review-area:not(:has(.review-content))':
    {
      height: 'var(--staircase-reviews-height)',
    },
}

export default (theme) => ({
  [`@media (max-width: ${theme.breakpoints.md})`]: mobileStyles,
  [`@media (min-width: ${theme.breakpoints.md})`]: desktopStyles,
})
