export default {
  parts: [
    'horizontalFilterButton',
    'activeFilterButton',
    'iconSize',
    'activeFilterCount',
    'FilterButtonsWrapper',
    'FilterButtons',
    'filterPriceSeparator',
  ],
  baseStyle: ({ theme }) => ({
    horizontalFilterButton: {
      ...theme.typography['text-body1-m'],
      backgroundColor: 'var(--color-background-filter-pill-default, #FFFFFF)',
      padding: 'var(--spacing-3) 10px var(--spacing-3) var(--spacing-4)',
      color: 'var(--color-text-filter-pill-default, #333333)',
      textTransform: 'capitalize',
      borderRadius: '800px',
      border: 'var(--border-width-s) solid var(--color-border-filter-pill-default, #E1E1E1)',
      minWidth: 'auto',
      height: 'var(--spacing-12)',
      gap: '3px',
      '&:hover:not(:disabled)': {
        paddingLeft: '15px',
        paddingRight: '9px',
        borderWidth: 'var(--border-width-m)',
        backgroundColor: 'var(--color-background-filter-pill-hover, #FFFFFF)',
        borderColor: 'var(--color-border-filter-pill-hover, #000000)',
        color: 'var(--color-text-filter-pill-hover, #000000)',
      },
      '&:focus-visible': {
        paddingLeft: '15px',
        paddingRight: '9px',
        backgroundColor: 'var(--color-background-filter-pill-focus, #FFFFFF)',
        borderColor: 'var(--color-border-filter-pill-focus, #EE0011)',
        color: 'var(--color-text-filter-pill-label-focus, #000000)',
        borderWidth: 'var(--border-width-m)',
        boxShadow: 'none',
      },
      '&:disabled': {
        backgroundColor: 'var(--color-background-filter-pill-disabled, #D8D8D8)',
        borderColor: 'var(--color-border-filter-pill-disabled, #D8D8D8)',
        color: 'var(--color-text-filter-pill-disabled, #949494)',
        opacity: '1',

        '&:hover': {
          backgroundColor: 'var(--color-background-filter-pill-disabled, #D8D8D8)',
        },
      },
    },
    activeFilterButton: {
      paddingLeft: '15px',
      paddingRight: '9px',
      borderWidth: 'var(--border-width-m)',
      borderColor: 'var(--color-border-filter-pill-selected, #000000)',
      color: 'var(--color-text-filter-pill-selected, #000000)',
    },
    iconSize: {
      width: '24px',
      height: '24px',
    },
    activeFilterCount: {
      ...theme.typography['text-body1-s'],
      fontFamily: 'var(--font-face1-bold)',
      backgroundColor: 'var(--color-background-filter-pill-counter, #000000)',
      paddingTop: '5px',
      paddingBottm: 'var(--spacing-1)',
      width: 'var(--spacing-6)',
      height: 'var(--spacing-6)',
      marginRight: '6px',
      color: 'var(--color-text-filter-pill-counter, #FFFFFF)',
      borderRadius: 'var(--border-radius-full)',
    },
    filterPopup: {
      position: 'absolute',
      zIndex: '20',
      backgroundColor: 'var(--color-white-base)',
      paddingY: '36px',
      marginTop: 'var(--spacing-2)',
      borderRadius: 'var(--border-radius-m)',
      boxShadow: '0 0 33px 5px var(--color-black-10)',
    },
    filterPopupContent: {
      height: '100%',
      maxHeight: '360px',
      overflowY: 'scroll',
      paddingX: 'var(--spacing-6) var(--spacing-4)',
      paddingLeft: 'var(--spacing-6)',
      paddingRight: 'var(--spacing-4)',
      marginRight: 'var(--spacing-1)',
      '::-webkit-scrollbar': {
        width: 'var(--spacing-1)',
      },
      '::-webkit-scrollbar-thumb': {
        borderRadius: '2px',
        backgroundColor: 'var(--color-neutral-light-3)',
      },
    },
    closePopupButton: {
      padding: '0',
      position: 'absolute',
      top: 'var(--spacing-2)',
      right: 'var(--spacing-2)',
    },
    filterColorButtonWrapper: {
      gap: 'var(--spacing-4)',
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      '& a, & button': {
        ...theme.typography['text-body1-m'],
        minWidth: '113px',
        padding: 'var(--spacing-2) var(--spacing-3)',
        height: 'var(--spacing-12)',
        borderColor: 'var(--color-neutral-light-2)',
        borderRadius: '800px',
        color: 'var(--color-neutral-dark)',
        backgroundColor: 'var(--color-white-base)',
        justifyContent: 'left',
        gap: 'var(--spacing-2)',
        textTransform: 'capitalize',
        '& div': {
          position: 'unset',
          width: 'var(--spacing-6)',
          height: 'var(--spacing-6)',
          border: '1px solid var(--color-neutral-light-3)',
          borderRadius: 'var(--border-radius-full)',
        },
        '&:hover:not(:disabled)': {
          borderWidth: '2px',
          borderColor: 'var(--color-black-base)',
          padding: '7px 11px',
          '& div': {
            width: 'var(--spacing-6)',
            height: 'var(--spacing-6)',
          },
        },
        '&.selected': {
          borderColor: 'var(--color-black-base)',
          borderWidth: '2px',
          backgroundColor: 'var(--color-white-base)',
          padding: '7px 11px',
          '& div': {
            width: 'var(--spacing-6)',
            height: 'var(--spacing-6)',
          },
        },
      },
    },
    FilterButtonsWrapper: {
      gap: 'var(--spacing-4)',
      '&.sizes': {
        a: {
          minWidth: '83px',
          padding: 'var(--spacing-3) var(--spacing-6)',
          justifyContent: 'center',
          color: 'var(--color-black-base)',
          borderColor: 'var(--color-neutral-inactive)',
          '& > div': {
            display: 'none',
          },
          '&:hover': {
            padding: '11px 23px',
            borderColor: 'var(--color-black-base)',
          },
          '&.selected': {
            padding: '11px 23px',
            borderColor: 'var(--color-black-base)',
          },
          '&[disabled]': {
            color: 'var(--color-neutral-base)',
            borderColor: '#E6E6E6',
            '&::after': {
              background:
                'linear-gradient(to right bottom, transparent calc(50% - 1px), #E6E6E6, transparent calc(50% + 1px))',
            },
          },
        },
      },
    },
    FilterButtons: {
      minWidth: '220px',
      padding: 'var(--spacing-2) var(--spacing-4)',
      paddingLeft: 'var(--spacing-3)',
      height: 'var(--spacing-12)',
      borderColor: 'var(--color-neutral-light-2)',
      borderRadius: '800px',
      color: 'var(--color-neutral-dark)',
      lineHeight: 'var(--line-height-140)',
      backgroundColor: 'var(--color-white-base)',
      justifyContent: 'left',
      gap: 'var(--spacing-2)',
      svg: { color: 'var(--color-white-base)' },
      '&:focus': {
        borderColor: 'var(--color-neutral-light-2)',
      },
      '&:hover': {
        borderWidth: '2px',
        borderColor: 'var(--color-black-base)',
        padding: '7px 15px',
        paddingLeft: '11px',
        div: {
          backgroundColor: 'var(--color-neutral-light-3)',
          borderColor: 'var(--color-neutral-light-3)',
        },
      },
      '&.selected': {
        borderColor: 'var(--color-black-base)',
        borderWidth: '2px',
        backgroundColor: 'var(--color-white-base)',
        padding: '7px 15px',
        paddingLeft: '11px',
        div: {
          backgroundColor: 'var(--color-black-base)',
          borderColor: 'var(--color-black-base)',
        },
        '&:focus': {
          borderColor: 'var(--color-black-base)',
        },
      },
      '&[disabled]': {
        color: 'var(--color-neutral-base)',
        opacity: 1,
        pointerEvents: 'none',
        '&::after': {
          content: '""',
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          borderRadius: '800px',
          background:
            'linear-gradient(to right bottom, transparent calc(50% - 1px), var(--color-neutral-light-2), transparent calc(50% + 1px))',
        },
      },
    },
    filterPriceSeparator: {
      width: 'var(--spacing-4)',
      height: '2px',
      backgroundColor: 'var(--color-inactive)',
    },
    filterPriceFieldsWrapper: {
      gap: 'var(--spacing-3)',
      alignItems: 'center',
      marginTop: '5px',
    },
  }),
  variants: {
    shopBy: ({ theme }) => ({
      horizontalFilterButton: {
        [`@media (min-width: ${theme.breakpoints.md})`]: {
          padding: 'var(--spacing-2) var(--spacing-4)',
          color: 'var(--color-black-base)',
          gap: 'var(--spacing-2)',
          '& svg': {
            width: 'var(--spacing-4)',
            height: 'var(--spacing-4)',
            fill: 'var(--color-icon-filter-pill-default)',
            stroke: 'var(--color-icon-filter-pill-default)',
            strokeWidth: '0.5px',
          },
          '&:hover:not(:disabled)': {
            paddingLeft: '15px',
            paddingRight: '15px',
          },
        },
      },
    }),
  },
}
