export default {
  parts: [
    'expendedNavbarContainer',
    'menuMobileContentarea',
    'contentDividerContainer',
    'mobileMenuDrawerContainer',
    'contentContainer',
    'drawerWrapper',
    'menuBody',
    't1ItemWrapper',
    't1Item',
    't1ItemText',
    'menuFooterLinks',
    'navLink',
    'navLinkSVG',
    'countryLabelStyle',
    'accordionWrapper',
    'accordion',
    'accordionItem',
    'accordionItemBox',
    'subCategoryAccordionItemBox',
    'buttonWrapper',
    'buttonContent',
    'noBackground',
    'selectedCategory',
    'accordionPanel',
    'closeButton',
    'navFlyoutPromoContent',
    'navFlyoutCTAButton',
    'mobileMenuContainer',
    't1VerticalList',
    't1VerticalRow',
    't1VerticalChevron',
    't1VerticalText',
    'tierTwoFY26AccordionButton',
    'tierTwoFY26ButtonContent',
    'tierTwoFY26LeafRow',
    'footerFY26',
    'footerFY26Link',
  ],
  baseStyle: ({ theme }) => ({
    drawerWrapper: {
      '&.default': {
        maxWidth: '512px',
        '@media (max-width: 544px)': {
          maxWidth: `calc(100% - ${theme.space.xxl})`,
        },
      },
      display: 'flex',
      flexDirection: 'column',
      position: 'relative',
      width: '100%',
      outline: '0px',
      zIndex: 'var(--chakra-zIndices-modal)',
      maxHeight: '100vh',
      background: 'var(--chakra-colors-white)',
      color: 'inherit',
      boxShadow: 'var(--chakra-shadows-lg)',
      height: '100vh',
    },
    menuMobileContentarea: {
      px: 'm',
      py: 'l',
      bg: theme.colors.neutral.light,
    },
    menuIconContainer: {
      mr: theme.space.s,
      position: 'absolute',
      top: 0,
      left: 0,
    },
    expendedNavbarContainer: {
      p: `${theme.space.mar} ${theme.space.m}`,
    },
    contentDividerContainer: {
      my: 'm',
    },
    mobileMenuDrawerContainer: (isOpen) => ({
      opacity: isOpen ? '1' : '0',
      position: 'fixed',
      left: '0px',
      top: '0px',
      width: '100vw',
      height: '100dvh',
      background: 'var(--chakra-colors-blackAlpha-600)',
      zIndex: 'var(--chakra-zIndices-overlay)',
      transition: 'opacity 0.3s',
    }),
    contentContainer: {
      display: 'flex',
      width: '100vw',
      height: '100dvh',
      position: 'fixed',
      left: '0px',
      top: '0px',
      zIndex: 'var(--chakra-zIndices-modal)',
      background: 'var(--color-scrim-dark)',
      '-webkit-box-pack': 'center',
      justifyContent: 'center',
    },
    menuBody: {
      flex: '1 1 0%',
      overflow: 'auto',
      padding: '0px',
    },
    button: {
      borderRadius: 'var(--border-radius-xs)',
      borderStyle: 'solid',
      textTransform: 'uppercase',
      fontWeight: 400,
      WebkitTapHighlightColor: 'transparent',
      fontFamily: 'var(--font-face1-normal)',
      width: '32px',
      height: '32px',
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      zIndex: 1,
      '& > button': {
        margin: '0 auto',
        position: 'relative',
        '&::before': {
          top: 0,
          left: 0,
          opacity: 0,
          zIndex: -1,
          content: '""',
          width: '100%',
          height: '100%',
          filter: 'blur(0px)',
          position: 'absolute',
          borderRadius: 'inherit',
          backgroundColor: 'silver',
        },
        '&:active::before, &:focus::before': {
          filter: 'blur(2px)',
          opacity: 0.05,
        },
      },
    },
    closeButton: {
      outline: '0px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: '0',
      borderRadius: 'var(--chakra-radii-md)',
      transition: 'all 0.2s ease 0s',
      width: 'var(--spacing-6)',
      height: 'var(--spacing-6)',
      marginBottom: 'var(--spacing-6)',
      fontSize: '10px',
      position: 'absolute',
      top: 'var(--chakra-space-2)',
      right: 'unset',
      color: 'var(--color-white-base)',
      zIndex: 'var(--chakra-zIndices-popover)',
      left: 'calc(100vw - var(--spacing-8))',
      '-webkit-box-align': 'center',
      '-webkit-box-pack': 'center',
      '& svg': {
        display: 'inline-block',
        lineHeight: '1em',
        flexShrink: '0',
        color: 'currentcolor',
        fill: 'white',
        verticalAlign: 'middle',
        width: 'var(--spacing-6)',
        height: 'var(--spacing-6)',
      },
    },
  }),
  variants: {
    mobileMenuV2: ({ theme }) => ({
      expendedNavbarContainer: {
        p: 0,
      },
      mobileMenuContainer: {
        zIndex: '1000',
        height: '120dvh',
        position: 'absolute',
        border: '1px solid  #F0F0F0',
      },
      drawerWrapper: {
        '&.default': {
          maxWidth: '512px',
          '@media (max-width: 544px)': {
            maxWidth: `calc(100% - ${theme.space.xxl})`,
          },
        },
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
        width: '100%',
        outline: '0px',
        zIndex: 'var(--chakra-zIndices-modal)',
        maxHeight: '100dvh',
        background: 'var(--scheme-bg-color)',
        color: 'inherit',
        boxShadow: 'none',
        height: '100vh',
      },
      mobileMenuDrawerContainer: (isOpen) => ({
        opacity: isOpen ? '1' : '0',
        position: 'fixed',
        left: '0px',
        top: '0px',
        width: '100vw',
        height: '120dvh',
        background: 'var(--chakra-colors-blackAlpha-600)',
        zIndex: 'var(--chakra-zIndices-overlay)',
        transition: 'opacity 0.3s',
        border: '1px solid  #F0F0F0',
      }),
      contentContainer: {
        display: 'flex',
        width: '100vw',
        height: '120dvh',
        position: 'fixed',
        left: '0px',
        top: '0px',
        zIndex: 'var(--chakra-zIndices-modal)',
        background: 'var(--color-neutral-light-1, #F0F0F0)',
        '-webkit-box-pack': 'center',
        justifyContent: 'center',
      },
      navFlyoutPromoContent: {
        p: 'var(--spacing-4)',
        pt: 'var(--spacing-6)',
        pb: 0,
        img: {
          width: '100%',
        },
      },
      navFlyoutCTAButton: {
        w: '100%',
        mt: 'var(--spacing-3)',
        borderRadius: 'var(--border-radius-s)',
        background: 'var(--color-secondary)',
        boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 'var(--spacing-2)',
        alignSelf: 'stretch',
        '& p': {
          fontFamily: 'var(--font-face1-bold)',
          textTransform: 'none',
        },
      },
      t1ItemWrapper: {
        borderBottom: '2px solid var(--scheme-t1-subline-color)',
        paddingRight: '24px',
        py: '12px',
      },
      t1Item: {
        '&.active': {
          borderBottom: '2px solid var(--scheme-text-color)',
          paddingBottom: '14px', // padding of the wrapper + border width
          marginBottom: '-14px',
        },
      },
      t1ItemText: {
        '&.active': {
          fontWeight: 700,
        },
        fontWeight: 400,
        color: 'var(--scheme-text-color)',
        fontSize: 'var(--text-16)',
        fontStyle: 'normal',
        lineHeight: 'var(--line-height-l)',
        letterSpacing: '0.2px',
      },
      menuFooterLinks: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        bottom: '0',
        backgroundColor: 'var(--scheme-footer-bg-color)',
        padding: 'var(--spacing-4)',
        position: 'fixed',
        zIndex: '1300',
        '& svg use[href="#icon-accountV2"]': {
          transform: 'translateY(-4px) translateX(-3px) scale(1.3)',
          fill: 'var(--scheme-text-color)',
        },
        '& svg use[href="#icon-packageV2"], & svg use[href="#icon-feedback"]': {
          transform: 'translateY(-3px) scale(1.2)',
        },
      },
      countryLabelStyle: {
        '& svg': { height: '20px', width: '20px', transform: 'scale(1.25)' },
      },
      navLink: {
        minWidth: '75px',
        width: 'auto',
        height: '36px',
        marginRight: 0,
      },
      navLinkSVG: {
        '& svg': {
          height: '20px',
          width: '20px',
          '& path': {
            fill: 'currentColor',
            stroke: 'currentColor',
          },
        },
      },
      accordionWrapper: {
        height: '100%',
        overflowY: 'auto',
        '& svg path': {
          fill: 'var(--scheme-text-color)',
          stroke: 'var(--scheme-text-color)',
        },
      },
      accordion: {
        width: '100%',
        mt: 'var(--spacing-4)',
        mb: 'var(--spacing-20)',
      },
      accordionItem: {
        border: 'none',
        width: '100%',
      },
      accordionItemBox: {
        width: '100%',
        px: 'var(--spacing-4)',
      },
      subCategoryAccordionItemBox: {
        width: '100%',
        px: 'var(--spacing-8)',
      },
      buttonContent: {
        flexGrow: '1',
        height: '48px',
        display: 'flex',
        textAlign: 'left',
        alignItems: 'center',
        color: 'var(--scheme-text-color)',
        fontSize: 'var(--text-20)',
        lineHeight: 'var(--line-height-l)',
        fontFamily: 'var(--font-face1-normal)',
        fontWeight: 'normal',
        letterSpacing: '0.2px',
      },
      buttonWrapper: {
        display: 'flex',
        justifyContent: 'space-around',
        alignItems: 'center',
        width: '100%',
        _active: {
          backgroundColor: 'var(--scheme-selected-category-bg)',
        },
      },
      noBackground: {
        _active: {
          backgroundColor: 'none',
        },
        _hover: {
          backgroundColor: 'none',
        },
      },
      selectedCategory: {
        backgroundColor: 'var(--scheme-selected-category-bg)',
      },
      accordionButton: {
        display: 'flex',
        justifyContent: 'space-between',
        minHeight: '48px',
        px: 'var(--spacing-4)',
      },
      accordionPanel: {
        px: '0',
        py: '0',
      },
      closeButton: {
        position: 'relative',
      },
      menuBody: {
        position: 'relative',
      },
      t1VerticalList: {
        width: '100%',
        flexDirection: 'column',
        px: 'var(--spacing-4)',
        pb: 'var(--spacing-2)',
      },
      t1VerticalRow: {
        width: '100%',
        minHeight: '48px',
        py: 'var(--spacing-2)',
        borderBottom: '1px solid var(--scheme-t1-subline-color, rgba(0,0,0,0.12))',
        cursor: 'pointer',
        color: 'var(--scheme-text-color)',
        _focusVisible: {
          outline: '2px solid var(--color-secondary, #000)',
          outlineOffset: '2px',
        },
      },
      t1VerticalChevron: {
        flexShrink: 0,
        display: 'flex',
        alignItems: 'center',
        color: 'var(--scheme-text-color)',
      },
      t1VerticalText: {
        color: 'var(--scheme-text-color)',
        fontSize: 'var(--text-16)',
        lineHeight: 'var(--line-height-l)',
        fontFamily: 'var(--font-face1-normal)',
        letterSpacing: '0.2px',
      },
      tierTwoFY26AccordionButton: {
        minHeight: '44px',
        py: 0,
      },
      tierTwoFY26ButtonContent: {
        fontSize: 'var(--text-16)',
        lineHeight: '29px',
        minHeight: 'auto',
      },
      tierTwoFY26LeafRow: {
        minHeight: '44px',
      },
      footerFY26: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        columnGap: 'var(--spacing-4)',
        rowGap: 'var(--spacing-3)',
        pt: 'var(--spacing-4)',
        pb: 'calc(var(--spacing-4) + env(safe-area-inset-bottom, 0px))',
      },
      footerFY26Link: {
        minWidth: '56px',
        width: 'auto',
        marginRight: 0,
      },
    }),
  },
}
