export default {
  baseStyle: ({ theme }) => ({
    containerWrapper: {
      backgroundColor: 'var(--color-neutral-light-1)',
      p: '0 14px var(--spacing-6)',
    },
    container: {
      p: 'var(--spacing-8) var(--spacing-6)',
      backgroundColor: 'var(--color-white-base)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      borderRadius: '18.3px',
      gap: 'var(--spacing-4)',
      position: 'relative',
    },
    mainTitle: {
      ...theme.typography['text-display4-s'],
      fontFamily: 'var(--font-face1-extended-bold)',
      color: 'var(--color-black-base)',
      textAlign: 'center',
      fontWeight: '700',
      fontSize: 'var(--text-24)',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-s)',
    },
    searchInputContainer: {
      backgroundColor: 'var(--color-neutral-light)',
      borderRadius: 'var(--border-radius-l)',
      padding: 'var(--spacing-4)',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      h: '58px',
      zIndex: '5',
    },
    searchIcon: {
      marginRight: 'var(--spacing-2)',
      marginBottom: 'var(--spacing-1)',
    },
    searchInput: {
      p: '1px 0 0',
      border: 'none',
      outline: 'none',
      borderRadius: 'none',
      h: 'auto',
      color: 'var(--color-text-primary)',
      flex: '1',
      backgroundColor: 'transparent',
      ...theme.typography['text-title1-m'],
      fontFamily: 'var(--font-face1-extended-normal)',
      fontSize: 'var(--text-14)',
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: '125%',
      letterSpacing: 'var(--letter-spacing-xs)',
      '&:focus-visible': {
        outline: 'none',
        border: 'none',
        boxShadow: 'none',
      },
    },
    invalidSearchTermContainer: {
      position: 'absolute',
      backgroundColor: 'var(--color-white-base)',
      top: '118px',
      left: 'var(--spacing-6)',
      right: 'var(--spacing-6)',
      borderRadius: '0px 0px var(--border-radius-l) var(--border-radius-l)',
      padding: 'var(--spacing-4)',
      paddingTop: 'var(--spacing-8)',
      zIndex: '4',
      boxShadow: 'var(--shadow-b)',
      display: 'flex',
      flexDirection: 'row',
      gap: 'var(--spacing-3)',
      alignItems: 'center',
      '@keyframes slideIn': {
        from: {
          transform: 'translateY(-50%)',
        },
        to: {
          transform: 'translateY(0)',
        },
      },
      animation: 'slideIn',
      animationDuration: '400ms',
      animationFillMode: 'forwards',
    },
    invalidSearchTermText: {
      ...theme.typography['text-body1-m'],
      fontWeight: '400',
    },
    trendingSection: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--spacing-3)',
    },
    trendingSectionTitle: {
      ...theme.typography['text-title2-s'],
      color: 'var(--color-neutral-dark-1)',
      fontWeight: 700,
    },
    pillsWrapper: {
      position: 'relative',
      overflow: 'hidden',
      '&::before, &::after': {
        content: '""',
        position: 'absolute',
        top: 0,
        width: '20px',
        height: '100%',
        zIndex: 1,
        pointerEvents: 'none',
      },
      '&::before': {
        left: 0,
        background:
          'linear-gradient(270deg, rgba(255, 255, 255, 0.00) 0%, var(--color-white-base) 100%)',
      },
      '&::after': {
        right: 0,
        background:
          'linear-gradient(90deg, rgba(255, 255, 255, 0.00) 0%, var(--color-white-base) 100%)',
      },
      '&.leftFadeHidden::before': {
        width: 0,
      },
      '&.rightFadeHidden::after': {
        width: 0,
      },
    },
    pillsContainer: {
      display: 'flex',
      gap: 'var(--spacing-1)',
      overflowX: 'auto',
      scrollbarWidth: 'none',
      msOverflowStyle: 'none',
      '&::-webkit-scrollbar': {
        display: 'none',
      },
    },
    pill: {
      backgroundColor: 'var(--color-background-filter-pill-default)',
      border: '1px solid var(--color-black-10)',
      borderRadius: '800px',
      padding: '17px var(--spacing-6)',
      whiteSpace: 'nowrap',
      ...theme.typography['text-cta2-xs'],
      textAlign: 'center',
    },
  }),
}
