export default {
  baseStyle: ({ theme }) => ({
    containerWrapper: {
      backgroundColor: 'var(--color-neutral-light-1)',
      p: '0 14px',
    },
    container: {
      p: 'var(--spacing-8) var(--spacing-6)',
      backgroundColor: 'var(--color-white-base)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      borderRadius: '18.3px',
      gap: 'var(--spacing-4)',
      position: 'relative',
    },
    mainTitle: {
      ...theme.typography['text-display4-ms'],
      color: 'var(--color-black-base)',
      fontFamily: 'var(--font-face2-normal)',
      fontSize: 'var(--text-28)',
      fontStyle: 'italic',
      fontWeight: 400,
      lineHeight: '100%',
    },
    searchInputContainer: {
      backgroundColor: 'var(--color-product-image-bg)',
      borderRadius: 'var(--border-radius-l)',
      padding: 'var(--spacing-4) var(--spacing-4) 15px',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      h: '58px',
      zIndex: '5',
    },
    searchIcon: {
      marginRight: 'var(--spacing-2)',
    },
    searchInput: {
      p: '1px 0 0',
      border: 'none',
      outline: 'none',
      h: 'auto',
      flex: '1',
      borderRadius: 'none',
      backgroundColor: 'transparent',
      ...theme.typography['text-title1-s'],
      color: 'var(--color-neutral-dark)',
      fontFamily: 'var(--font-face1-light)',
      fontSize: 'var(--text-14)',
      fontWeight: 400,
      lineHeight: '125%',
      '&:focus-visible': {
        outline: 'none',
        border: 'none',
        boxShadow: 'none',
      },
    },
    trendingSection: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--spacing-3)',
    },
    trendingSectionTitle: {
      ...theme.typography['text-body3-l'],
      color: 'var(--neutral-grey-900, #161616)',
      fontWeight: 400,
      fontSize: 'var(--text-16)',
      lineHeight: 'var(--line-height-140)',
    },
    invalidSearchTermContainer: {
      position: 'absolute',
      backgroundColor: 'var(--color-white-base)',
      top: '118px',
      left: 'var(--spacing-6)',
      right: 'var(--spacing-6)',
      borderRadius: '0px 0px var(--border-radius-l) var(--border-radius-l)',
      padding: 'var(--spacing-4)',
      paddingTop: 'var(--spacing-8)',
      zIndex: '4',
      boxShadow: 'var(--shadow-b)',
      display: 'flex',
      flexDirection: 'row',
      gap: 'var(--spacing-3)',
      alignItems: 'center',
      '@keyframes slideIn': {
        from: {
          transform: 'translateY(-50%)',
        },
        to: {
          transform: 'translateY(0)',
        },
      },
      animation: 'slideIn',
      animationDuration: '400ms',
      animationFillMode: 'forwards',
    },
    invalidSearchTermText: {
      ...theme.typography['text-title1-s'],
      fontWeight: '400',
    },
    pillsWrapper: {
      position: 'relative',
      overflow: 'hidden',
      '&::before, &::after': {
        content: '""',
        position: 'absolute',
        top: '-0.8px',
        width: '37px',
        height: '38px',
        zIndex: 1,
        pointerEvents: 'none',
      },
      '&::before': {
        left: '-3.72px',
        background:
          'linear-gradient(270deg, rgba(255, 255, 255, 0.00) 0%, var(--color-white-base) 100%)',
      },
      '&::after': {
        right: '-3.72px',
        background:
          'linear-gradient(90deg, rgba(255, 255, 255, 0.00) 0%, var(--color-white-base) 100%)',
      },
      '&.leftFadeHidden::before': {
        width: 0,
      },
      '&.rightFadeHidden::after': {
        width: 0,
      },
    },
    pillsContainer: {
      display: 'flex',
      gap: 'var(--spacing-1)',
      overflowX: 'auto',
      scrollbarWidth: 'none',
      msOverflowStyle: 'none',
      '&::-webkit-scrollbar': {
        display: 'none',
      },
    },
    pill: {
      backgroundColor: 'var(--color-background-filter-pill-default)',
      border: '1px solid var(--color-black-10)',
      borderRadius: '800px',
      padding: '13px var(--spacing-6)',
      h: '48px',
      whiteSpace: 'nowrap',
      ...theme.typography['text-body2-m'],
      textAlign: 'center',
      color: 'var(--color-black-base)',
      fontSize: 'var(--text-14)',
      fontWeight: 500,
      lineHeight: '135%',
    },
  }),
}
