const CONTAINER_HEIGHT = '620px'
const CARD_HEIGHT = '385px'

export default {
  baseStyle: ({ theme }) => ({
    container: {
      overflow: 'hidden',
      position: 'relative',
      width: '100%',
      minHeight: CONTAINER_HEIGHT,
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--spacing-4)',
      paddingBottom: 'var(--spacing-6)',
      paddingTop: 'var(--spacing-6)',
      background: 'var(--color-white-base)',
    },
    header: {
      display: 'flex',
      gap: '7px',
      flexDirection: 'column',
      alignItems: 'center',
    },
    heading: {
      ...theme.typography['text-display4-s'],
      fontWeight: 400,
    },
    subHeading: {
      ...theme.typography['text-body1-m'],
      fontWeight: 'normal',
      color: 'var(--color-neutral-medium)',
    },
    stack: {
      position: 'absolute',
      top: '96px',
      width: '100vw',
      height: CARD_HEIGHT,
    },
    footer: {
      display: 'flex',
      flexDirection: 'column',
      textAlign: 'center',
      gap: 'var(--spacing-4)',
    },
    clear: {
      marginTop: '415px',
      marginBottom: '-4px',
    },
    counter: {
      ...theme.typography['text-body1-l'],
      fontWeight: '400',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-s)',
    },
    buttonThumbs: {
      display: 'flex',
      gap: 'var(--spacing-6)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    card: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      height: '100%',
      width: 'calc(100% - var(--spacing-6))',
      borderRadius: 'var(--spacing-4)',
      overflow: 'hidden',
      position: 'absolute',
      left: 'var(--spacing-3)',
      right: 'var(--spacing-3)',
      transitionProperty: 'transform, background-color filter',
      transitionTimingFunction: 'cubic-bezier(var(--transition-easing-gentle))',
      transitionDuration: '150ms',
      backgroundColor: '#F0F0F0',
      transformOrigin: 'bottom',
      border: '1px solid var(--color-neutral-light-2)',
    },
    imageContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      userSelect: 'none',
      marginBottom: '20px',
    },
    image: {
      height: '278px',
    },
    productName: {
      position: 'relative',
      bottom: 'var(--spacing-6)',
      ...theme.typography['text-body1-l'],
      fontWeight: '400',
      color: 'var(--color-black-base)',
      marginLeft: 'var(--spacing-4)',
      marginRight: 'var(--spacing-4)',
      zIndex: 10,
      textAlign: 'center',
      display: '-webkit-box',
      lineClamp: 1,
      WebkitLineClamp: 1,
      WebkitBoxOrient: 'vertical',
      whiteSpace: 'normal',
      overflow: 'hidden',
    },
    productButton: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '10px var(--spacing-3)',
      minWidth: '110px',
      minHeight: '39px',
      ...theme.typography['text-cta2-xxs'],
      lineHeight: '1.6',
      color: 'var(--color-black-base)',
      backgroundColor: 'var(--color-white-base)',
      border: '1px solid var(--color-neutral-light-2, #e1e1e1)',
      borderRadius: '130px',
      '&:hover': {
        backgroundColor: '#f0f9ff',
      },
      '&:active': {
        background: '#e0f2fe',
      },
    },
    thumb: {
      display: 'flex',
      p: 'var(--spacing-4)',
      bg: 'black',
      h: 'var(--spacing-12)',
      w: 'var(--spacing-12)',
      borderRadius: 'var(--border-radius-full)',
      transition: 'all 300ms linear',
      path: {
        fill: 'white',
      },
    },
    thumbLike: {
      '&:focus:not(:disabled)': {
        background: 'var(--color-success-primary)',
      },
      '&:hover:not(:disabled)': {
        background: 'var(--color-success-primary)',
      },
    },
    thumbDisLike: {
      '&:focus:not(:disabled)': {
        background: '#C22121',
      },
      '&:hover:not(:disabled)': {
        background: '#C22121',
      },
    },
    gridContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      minHeight: CONTAINER_HEIGHT,
      animation: 'slidingFadeIn 300ms ease-in-out',
      paddingBottom: 'var(--spacing-6)',
      paddingTop: 'var(--spacing-6)',
      background: 'var(--color-neutral-light)',
      '@keyframes slidingFadeIn': {
        from: {
          transform: 'translateY(-3%)',
          opacity: 0,
        },
        to: {
          transform: 'translateY(0)',
          opacity: 1,
        },
      },
    },
    gridHeader: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--spacing-1)',
      alignItems: 'center',
      marginBottom: 'var(--spacing-4)',
      width: '100%',
      paddingLeft: 'var(--spacing-3)',
      paddingRight: 'var(--spacing-3)',
    },
    gridHeading: {
      ...theme.typography['text-display4-s'],
      fontWeight: 400,
      lineHeight: 'var(--line-height-120)',
    },
    gridSubHeading: {
      ...theme.typography['text-body1-m'],
      fontWeight: 'normal',
    },
    grid: {
      display: 'grid',
      columnGap: '8px',
      rowGap: 'var(--spacing-6)',
      width: '100vw',
      overflowX: 'auto',
      paddingBottom: 'var(--spacing-4)',
      paddingLeft: 'var(--spacing-3)',
      paddingRight: 'var(--spacing-3)',
    },
    gridItem: {
      position: 'relative',
      width: '100%',
      height: '140px',
      background: '#F0F0F0',
      borderRadius: 'var(--border-radius-l)',
      border: '1px solid var(--color-neutral-light-3)',
      overflow: 'hidden',
    },
    gridItemImage: {
      width: 'auto',
      maxHeight: '140px',
    },
    gridItemNotification: {
      position: 'absolute',
      top: '8px',
      left: '0',
      right: '0',
      display: 'flex',
      justifyContent: 'center',
    },
    gridItemNotificationText: {
      ...theme.typography['text-body1-s'],
      padding: '6px var(--spacing-4)',
      background: 'white',
      border: '1px solid rgba(0,0,0,0.05)',
      borderRadius: 'var(--border-radius-full)',
    },
    gridControls: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: 'auto',
    },
    startOverButton: {
      background: 'black',
      color: 'white',
      fontSize: 'var(--text-12)',
      lineHeight: 'var(--line-height-140)',
      padding: '12px var(--spacing-4)',
      borderRadius: 'var(--border-radius-full)',
      letterSpacing: '0.2px',
      textTransform: 'none',
      fontFamily: 'var(--font-face1-extended-normal)',
      marginTop: 'var(--spacing-1)',
    },
    messageContainer: {
      minHeight: CONTAINER_HEIGHT,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      textTransform: 'none',
      paddingBottom: 'var(--spacing-6)',
      paddingTop: 'var(--spacing-6)',
      background: 'var(--color-neutral-light-1)',
    },
    message: {
      ...theme.typography['text-body1-l'],
      textAlign: 'center',
      fontWeight: 'normal',
      maxWidth: '264px',
      color: 'var(--color-neutral-medium)',
    },
    messageControls: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: 'var(--spacing-6)',
    },
    skeletonStackCard1: {
      position: 'absolute',
      height: CARD_HEIGHT,
      left: 'var(--spacing-3)',
      width: 'calc(100% - 0.75rem - 0.75rem)',
      borderRadius: 'var(--spacing-3)',
      opacity: 1,
      zIndex: 3,
    },
    skeletonStackCard2: {
      position: 'absolute',
      height: CARD_HEIGHT,
      left: 'var(--spacing-3)',
      transform: 'translate3d(0px, 8px, 0px) scale(0.92)',
      transformOrigin: 'center bottom',
      width: 'calc(100% - 0.75rem - 0.75rem)',
      borderRadius: 'var(--spacing-3)',
      opacity: 1,
      zIndex: 2,
    },
    skeletonStackCard3: {
      height: CARD_HEIGHT,
      position: 'absolute',
      left: 'var(--spacing-3)',
      transform: 'translate3d(0px, 17px, 0px) scale(0.85)',
      transformOrigin: 'center bottom',
      width: 'calc(100% - 0.75rem - 0.75rem)',
      borderRadius: 'var(--spacing-3)',
      opacity: 1,
      zIndex: 1,
    },
    skeletonCount: {
      height: '19.2px',
      width: '50px',
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    skeletonGridContainer: {
      width: '100%',
    },
    skeletonGridImage: {
      height: '140px',
      width: '100%',
      marginBottom: '4px',
      borderRadius: 'var(--border-radius-l)',
    },
    skeletonGridPrice: {
      height: '30.8px',
      width: '70%',
    },
    listHeading: {
      ...theme.typography['text-display4-xxs'],
      textAlign: 'start',
      width: 'calc(100% - var(--spacing-6))',
      marginBottom: 'var(--spacing-2)',
      '&:not(:first-of-type)': {
        marginTop: 'var(--spacing-6)',
      },
    },
  }),
}
