export default {
  baseStyle: ({ theme }) => ({
    reviewOverlayContainer: () => ({
      flexDirection: 'column',
      p: '21px var(--spacing-8) var(--spacing-6)',
      position: 'absolute',
      backgroundColor: 'var(--color-scrim-dark)',
      bottom: 0,
      width: '100%',
      color: 'var(--color-secondary)',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        p: '14px var(--spacing-3) var(--spacing-4)',
        m: '0 var(--spacing-3) var(--spacing-10)',
        borderRadius: 'var(--border-radius-s)',
        backdropFilter: 'blur(10px)',
        minWidth: '351px',
        width: 'calc(100% - var(--spacing-3) * 2);',
      },
    }),
    reviewOverlayTitleContainer: {
      borderBottom: 'var(--border-width-s) solid var(--color-secondary)',
      flexDirection: 'row',
      justifyContent: 'space-between',
      pb: '9px',
      mb: '15px',
    },
    reviewOverlayTitle: {
      ...theme.typography['text-display1-l'],
      color: 'var(--color-secondary)',
      textAlign: 'center',
      leadingTrim: 'both',
      textEdge: 'cap',
      fontFamily: 'var(--font-face1-bold)',
      fontSize: 'var(--text-30)',
      fontStyle: 'normal',
      lineHeight: 1,
      letterSpacing: 'var(--letter-spacing-xs)',
      textTransform: 'capitalize',
    },
    reviewOverlayNameAndRatingContainer: {
      flexDirection: 'column',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        flexDirection: 'row',
        justifyContent: 'space-between',
      },
    },
    reviewOverlayNameText: {
      ...theme.typography['text-eyebrow1-m '],
      color: 'var(--color-secondary)',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-12)',
      fontStyle: 'normal',
      fontWeight: '400',
      textTransform: 'uppercase',
      lineHeight: 'var(--line-height-115)',
      letterSpacing: 'var(--letter-spacing-xl)',
      mb: '6px',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        fontSize: 'var(--text-10)',
        lineHeight: 'var(--line-height-135)',
        letterSpacing: 'var(--letter-spacing-l)',
        pt: '2px',
      },
    },
    reviewOverlayHeadline: {
      ...theme.typography['text-display1-xs'],
      color: 'var(--color-secondary)',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-20)',
      fontStyle: 'normal',
      fontWeight: '700',
      lineHeight: 1,
      letterSpacing: 'var(--letter-spacing-xs)',
      mt: '14px',
    },
    reviewOverlayComment: {
      height: '65px',
      overflowY: 'auto',
      overflowX: 'hidden',
      ...theme.typography['text-body1-s'],
      color: 'var(--color-secondary)',
      textOverflow: 'ellipsis',
      fontSize: 'var(--text-16)',
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 1,
      letterSpacing: 'var(--letter-spacing-xs)',
      fontFamily: 'var(--font-face1-normal)',
      mt: '10px',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        fontSize: 'var(--text-12)',
        lineHeight: 'var(--line-height-140)',
        textAlign: 'center',
      },
    },
    reviewOverlayButton: {
      ...theme.typography['text-cta1-s'],
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-12)',
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 'var(--line-height-115)',
      letterSpacing: 'var(--letter-spacing-xl)',
      textTransform: 'uppercase',
      w: '156px',
      alignSelf: 'center',
      borderRadius: 'var(--border-radius-xs)',
      border: 'var(--border-width-s) solid var(--color-primary)',
      background: 'var(--color-secondary)',
      mt: 'var(--spacing-4)',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        w: '100%',
        borderRadius: 'var(--border-radius-full)',
        border: 'var(--border-width-s) solid var(--color-neutral-inactive)',
        background: 'var(--color-white-base)',
        mt: '9px',
      },
    },
  }),
  variants: {
    reviewOverlayOnImageUpper: ({ theme }) => ({
      reviewOverlayContainer: () => ({
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          position: 'absolute',
          flexDirection: 'column',
          p: 'var(--spacing-3)',
          m: '0 var(--spacing-3)',
          borderRadius: 'var(--border-radius-s)',
          backdropFilter: 'blur(2.5px)',
          width: 'calc(100% - var(--spacing-3) * 2);',
          backgroundColor: 'var(--color-white-80)',
          bottom: 'var(--spacing-6)',
        },
      }),
      reviewOverlayRatingContainer: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          flexDirection: 'row',
          justifyContent: 'center',
          color: 'var(--color-black-base)',
          marginTop: 'var(--spacing-2)',
        },
      },
      reviewOverlayAverageRating: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-body1-s'],
          flexDirection: 'row',
          justifyContent: 'center',
          alignItems: 'center',
          '& > svg': {
            width: '13px',
            height: '13px',
            marginRight: '2px',
            marginTop: '-2px',
          },
        },
      },
      reviewOverlayRating: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-body1-s'],
          fontWeight: '400',
        },
      },
      reviewOverlayViewAllLink: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-link1-s'],
          color: 'var(--color-black-base)',
          textTransform: 'none',
          lineHeight: 'var(--line-height-140)',
          letterSpacing: 'var(--letter-spacing-xs)',
          textDecoration: 'underline',
          borderLeft: 'var(--border-width-s) solid var(--color-neutral-base)',
          pl: 'var(--spacing-2)',
          ml: 'var(--spacing-2)',
        },
      },
      reviewOverlayComment: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-body1-m'],
          color: 'var(--color-black-base)',
          marginTop: 'var(--spacing-1)',
          height: 'unset',
          textOverflow: 'ellipsis',
          overflow: 'hidden',
          display: '-webkit-box',
          WebkitLineClamp: 2,
          WebkitBoxOrient: 'vertical',
        },
      },
      reviewOverlayCloseButton: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          alignSelf: 'start',
          position: 'absolute',
          top: 'calc(-1 * var(--spacing-2))',
          right: 'calc(-1 * var(--spacing-2))',
          padding: '1.125rem', // missing in the design token
          '& > svg': {
            strokeWidth: '1.67px', // missing in the design token
            stroke: 'var(--color-black-base)',
            width: '10px', // missing in the design token
            height: '10px', // missing in the design token
            '$ > path': {
              fill: 'var(--color-black-base)',
            },
          },
        },
      },
      reviewOverlayTitle: {
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-badge1-xs'],
          color: 'var(--color-black-base)',
          textTransform: 'uppercase',
        },
      },
    }),
  },
}
