export default {
  baseStyle: ({ theme }) => ({
    tileWrapper: {
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        mr: 0,
        width: '54.7vw',
        minWidth: '54.7vw',
        maxWidth: 'fit-content',
      },
      width: '209px',
      maxWidth: '209px',
      position: 'relative',
    },
    tileImageWrapper: {
      bg: 'var(--color-neutral-light-1)',
      img: {
        objectFit: 'cover',
        height: 'var(--certona-desktop-product-tile-height)',
        width: '100%',
      },
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        h: 'auto',
        w: '100%',
        maxWidth: 'none',
        img: {
          h: 'inherit',
          w: 'inherit',
        },
      },
    },
    tileNameWrapper: {
      mt: 'var(--spacing-3)',
      mx: 'var(--spacing-2)',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        mx: 0,
        mt: 'var(--spacing-3)',
      },
      '& p': {
        textAlign: 'left',
        fontSize: 'var(--text-16)',
        fontFamily: theme.fontFamily.secondaryNormal,
        lineHeight: theme.lineHeights.xl,
        letterSpacing: theme.letterSpacings.xs,
        fontWeight: 'normal',
        color: theme.colors.main.black,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-body1-l'],
          fontFamily: theme.fontFamily.primaryNormal,
          fontSize: theme.fontSizes.md,
          lineHeight: theme.lineHeights.lg,
        },
      },
    },
    tilePriceWrapper: {
      px: 'var(--spacing-2)',
      width: '100%',
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'center',
      flexDirection: 'column',
      mt: 'var(--spacing-2)',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        px: 0,
        marginTop: '3px',
      },
    },
    tileComparablePriceWrapper: {
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        flexWrap: 'wrap',
        rowGap: 0,
      },
      gap: theme.space.s1,
      justifyContent: 'left',
      display: 'flex',
      '& p': {
        color: theme.colors.neutral.medium,
        [`@media (max-width: ${theme.breakpoints.sm})`]: {
          ...theme.typography['text-body1-s'],
          fontFamily: theme.fontFamily.primaryNormal,
          fontSize: theme.fontSizes.xs,
          fontWeight: '400',
          letterSpacing: theme.letterSpacings.xs,
          lineHeight: theme.lineHeights.xl,
        },
      },
    },
    tilePriceContainer: {
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        flexWrap: 'wrap',
        rowGap: 0,
      },
      display: 'flex',
      justifyContent: 'start',
      alignItems: 'baseline',
      gap: theme.space.xs,
    },
    tilePriceText: {
      fontSize: theme.fontSizes.sm,
      lineHeight: theme.lineHeights.xl,
      fontFamily: theme.fontFamily.secondaryNormal,
      letterSpacing: theme.letterSpacings.xs,
      fontWeight: 'normal',
      textAlign: 'left',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        ...theme.typography['text-body1-l'],
        fontFamily: theme.fontFamily.primaryNormal,
        fontSize: theme.fontSizes.md,
        lineHeight: theme.lineHeights.lg,
        letterSpacing: theme.letterSpacings.xs,
      },
    },
    tilePromotionsWrapper: {
      px: 'var(--spacing-2)',
      color: theme.colors.success.primary,
      fontSize: theme.fontSizes.sm,
      lineHeight: theme.lineHeights.xl,
      fontFamily: theme.fontFamily.secondaryNormal,
      letterSpacing: theme.letterSpacings.xs,
      fontWeight: 'normal',
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        ...theme.typography['text-body1-l'],
        px: 0,
        fontFamily: theme.fontFamily.primaryNormal,
        fontSize: theme.fontSizes.md,
        lineHeight: theme.lineHeights.lg,
        letterSpacing: theme.letterSpacings.xs,
      },
    },
    tileStrikeoffPrice: {
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        ...theme.typography['text-body1-m-line-through'],
        fontFamily: theme.fontFamily.primaryNormal,
        fontSize: theme.fontSizes.sm,
        lineHeight: theme.lineHeights.xl,
        letterSpacing: theme.letterSpacings.xs,
        color: theme.colors.neutral.medium,
        textDecoration: 'line-through',
      },
      fontSize: theme.fontSizes.sm,
      textDecoration: 'line-through',
      color: theme.colors.main.gray,
    },
    tileDiscount: {
      fontSize: theme.fontSizes.sm,
      [`@media (max-width: ${theme.breakpoints.sm})`]: {
        ...theme.typography['text-body1-m'],
        fontFamily: theme.fontFamily.primaryNormal,
        lineHeight: theme.lineHeights.xl,
        fontSize: theme.fontSizes.sm,
        letterSpacing: theme.letterSpacings.xs,
      },
    },
    saveForLaterPosition: {
      width: '24px',
      height: '24px',
      top: 'var(--spacing-2)',
      right: 'var(--spacing-2)',
    },
  }),
}
