export default {
  parts: [],
  baseStyle: ({ theme }) => ({
    modalWrapper: {
      [`@media (max-width: ${theme.maxLayoutWidth}px)`]: {
        right: theme.space.m,
      },
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        '--mobile-modal-width': '351px',
        width: 'var(--mobile-modal-width)',
        height: '138px',
        right: 'calc((100% - var(--mobile-modal-width)) / 2)',
      },
      position: 'fixed',
      right: `calc((100% - ${theme.maxLayoutWidth}px) / 2)`,
      top: '140px',
      width: '400px',
      height: '160px',
      zIndex: theme.zIndex.popover,
      boxShadow: 'var(--shadow-ltr)',
      background: 'var(--border-color-white-base)',
      animation: 'modalFadeIn 300ms cubic-bezier(0.62, 0.18, 0.38, 0.98)',
    },
    miniCartCloseButton: {
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        right: theme.space.xs,
        top: theme.space.xs,
      },
      position: 'absolute',
      right: theme.space.s,
      top: theme.space.s,
      '& svg': {
        width: '24px',
        height: '24px',
      },
    },
    contentWrapper: {
      position: 'relative',
      display: 'flex',
      justifyContent: 'space-between',
      height: '100%',
      '&::after': {
        content: "''",
        position: 'absolute',
        width: '100%',
        height: '3px',
        bottom: '0px',
        background: 'black',
      },
    },
    textContent: {
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        '--mobile-modal-image-width': '113px',
        width: 'calc(100% - var(--mobile-modal-image-width))',
      },
      '--desktop-modal-image-width': '127px',
      width: 'calc(100% - var(--desktop-modal-image-width))',
      padding: `${theme.space.s3} ${theme.space.s} ${theme.space.m} ${theme.space.s3}`,
    },
    image: {
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        height: '138px',
        width: '113px',
      },
      height: '160px',
      width: '127px',
    },
    modalTitle: {
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        fontSize: theme.fontSizes.lg,
        lineHeight: theme.lineHeights.s,
      },
      fontFamily: theme.fontFamily.primaryBold,
      fontSize: theme.fontSizes.xlg,
      letterSpacing: theme.letterSpacings.xs,
      lineHeight: theme.lineHeights.xs,
      marginRight: theme.space.l,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    modalText: {
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        fontSize: theme.fontSizes.md,
      },
      fontFamily: theme.fontFamily.secondaryNormal,
      fontSize: theme.fontSizes.lg,
      letterSpacing: theme.letterSpacings.xs,
      lineHeight: theme.lineHeights.xl,
      fontWeight: '400',
      display: '-webkit-box',
      lineClamp: '2',
      WebkitLineClamp: '2',
      WebkitBoxOrient: 'vertical',
      whiteSpace: 'normal',
      overflow: 'hidden',
    },
    viewBagBtn: {
      height: '40px',
      width: '100%',
      marginTop: theme.space.s,
      padding: `${theme.space.s3} ${theme.space.m}`,
      fontFamily: theme.fontFamily.primaryNormal,
      fontSize: theme.fontSizes.xs,
      letterSpacing: theme.letterSpacings.xl,
      lineHeight: theme.lineHeights.xs,
      textTransform: 'uppercase',
    },
  }),
}
