import { TemplateName } from 'toro/constants/templates'

export default {
  baseStyle: ({ theme }) => ({
    compareSimilarWrapper: {
      padding: 'var(--spacing-10) 0 var(--spacing-6)',
      flexDirection: 'column',
      backgroundColor: '#f1f1f1',
    },
    headerTitle: {
      fontFamily: 'var(--font-face1-extended-bold)',
      fontSize: 'var(--text-24)',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
      color: 'var(--color-primary)',
      marginBottom: '18px',
      marginLeft: 'var(--spacing-3)',
    },
    currentProductWrapper: {
      paddingX: 'var(--spacing-3)',
      boxShadow: '6px 0 10px -3px var(--color-black-10)',
      position: 'relative',
      zIndex: 1,
    },
    currentProductBadge: {
      position: 'absolute',
      top: '18px',
      width: '88px',
      backgroundColor: 'var(--color-white-base)',
      borderRadius: 'var(--spacing-10)',
      color: 'var(--color-black-base)',
      fontFamily: 'var(--font-face1-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-10)',
      letterSpacing: 'var(--letter-spacing-xs)',
      lineHeight: 1,
      textAlign: 'center',
      padding: '6px',
      left: '50%',
      marginRight: '-50%',
      transform: 'translate(-50%, -50%)',
      '&::after': {
        content: '""',
        position: 'absolute',
        display: 'block',
        width: '10px',
        height: '10px',
        margin: 'auto',
        left: 0,
        right: 0,
        top: '20px',
        borderLeft: '8px solid transparent',
        borderRight: '8px solid transparent',
        borderTop: '8px solid var(--color-white-base)',
      },
    },
    similarProductsWrapper: {
      width: '100%',
      overflow: 'hidden',
      overflowX: 'auto',
      '&::-webkit-scrollbar': {
        display: 'none',
      },
      '& a:last-of-type': {
        marginRight: 'var(--spacing-3)',
      },
    },
    productItem: {
      width: '34.8vw',
      minWidth: '34.8vw',
      maxWidth: '34.8vw',
      '&>div': {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
      },
    },
    productName: {
      ...theme.typography['text-body1-s'],
      fontFamily: 'var(--font-face1-extended-bold)',
      color: 'var(--color-primary)',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      marginTop: '10px',
      marginBottom: 'var(--spacing-1)',
      textAlign: 'center',
      maxWidth: '100%',
    },
    productColorImage: {
      width: '18px',
      height: '18px',
      borderRadius: '800px',
      '& img': {
        border: '1px solid var(--color-black-20)',
      },
    },
    colorText: {
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-12)',
      fontWeight: 400,
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
      textDecoration: 'underline',
      color: 'var(--color-neutral-medium)',
      marginLeft: 'var(--spacing-2)',
    },
    prictText: {
      fontFamily: 'var(--font-face1-extended-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-12)',
      lineHeight: 'var(--line-height-140)',
      letterSpacing: 'var(--letter-spacing-xs)',
      marginTop: 0,
      marginBottom: 'var(--spacing-1)',
      textAlign: 'center',
      '&:empty': {
        minHeight: '16.8px',
      },
    },
    productMaterialWrapper: {
      paddingTop: 'var(--spacing-4)',
      paddingBottom: 'var(--spacing-4)',
      borderTop: '1px solid var(--color-neutral-light-2)',
      mt: 'var(--spacing-3)',
    },
    productMaterialImage: {
      width: '100%',
      borderRadius: 'var(--border-radius-s)',
      marginBottom: '10px',
      '& img': {
        height: '38px',
        marginBottom: '0',
      },
    },
    productMaterialTitle: {
      fontFamily: 'var(--font-face1-bold)',
      fontSize: 'var(--text-10)',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
      marginBottom: '6px',
    },
    productMaterialItem: {
      fontFamily: 'var(--font-face1-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-12)',
      lineHeight: 'var(--line-height-140)',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    producWhatFitsInsideWrapper: {
      paddingTop: 'var(--spacing-3)',
      paddingBottom: '10px',
      borderTop: '1px solid var(--color-neutral-light-2)',
      textAlign: 'center',
      flexDirection: 'column',
      alignItems: 'center',
    },
    productWhatFitsInsideTitle: {
      fontFamily: 'var(--font-face1-bold)',
      fontSize: 'var(--text-10)',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
      marginTop: '10px',
      marginBottom: 'var(--spacing-2)',
    },
    productWhatFitsInsideItem: {
      fontFamily: 'var(--font-face1-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-10)',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
      '&:not(:last-of-type)': {
        marginBottom: '6px',
      },
    },
    productWhatFitsInsideItemWrapper: {
      display: 'flex',
      alignItems: 'center',
      textAlign: 'left',
      width: '100%',
      alignSelf: 'flex-start',
      gap: '8px',
      pl: 'calc((100% - 80px) / 2)',
      '&:not(:last-of-type)': {
        marginBottom: '6px',
      },
    },
    featuresWrapper: {
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
      paddingTop: 'var(--spacing-4)',
      paddingBottom: 'var(--spacing-4)',
      borderTop: '1px solid var(--color-neutral-light-2)',
    },
    featuresTitle: {
      ...theme.typography['text-cta3-xs'],
      fontWeight: 700,
      textAlign: 'center',
      display: 'flex',
    },
    featuresItems: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '6px',
    },
    featuresItem: {
      textAlign: 'center',
      leadingTrim: 'both',
      textEdge: 'cap',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-10)',
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    occasionWrapper: {
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
      paddingTop: 'var(--spacing-4)',
      paddingBottom: 'var(--spacing-4)',
      borderTop: '1px solid var(--color-neutral-light-2)',
    },
    occasionTitle: {
      ...theme.typography['text-cta3-xs'],
      fontWeight: 700,
      textAlign: 'center',
      display: 'flex',
    },
    occasionItems: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '6px',
    },
    occasionItem: {
      textAlign: 'center',
      leadingTrim: 'both',
      textEdge: 'cap',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-10)',
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    productMeasurementSpecsWrapper: {
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
      paddingTop: 'var(--spacing-4)',
      paddingBottom: 'var(--spacing-4)',
      borderTop: '1px solid var(--color-neutral-light-2)',
    },
    productMeasurementSpecsTitle: {
      color: 'var(--color-black-base)',
      textAlign: 'center',
      ...theme.typography['text-cta3-xs'],
      lineHeight: 'var(--line-height-100)',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '10px',
    },
    productMeasurementSpecsItem: {
      color: 'var(--color-black-base)',
      textAlign: 'center',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-10)',
      fontWeight: 400,
      lineHeight: 'var(--line-height-120)',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    viewMoreButton: {
      fontFamily: 'var(--font-face1-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-10)',
      lineHeight: 1,
      letterSpacing: 'var(--letter-spacing-xs)',
      textTransform: 'capitalize',
      backgroundColor: 'var(--color-black-base)',
      color: 'var(--color-white-base)',
      borderRadius: '130px',
      height: '28px',
      paddingLeft: '14px',
      paddingRight: '7px',
      marginTop: 'var(--spacing-8)',
      width: 'fit-content',
      alignSelf: 'center',
      svg: {
        path: { fill: 'var(--color-white-base)' },
      },
      '&:hover:not(:disabled)': {
        backgroundColor: 'var(--color-black-base)',
      },
    },
    gradient: {
      marginTop: '-40px',
      height: '40px',
      zIndex: 1,
    },
    skeletonImageWrapper: {
      aspectRatio: '4/5',
    },
    addToBagButtonWrapper: {
      marginTop: 'var(--spacing-3)',
    },
    addToBagButton: {
      button: {
        height: '36px',
        '& p': {
          fontSize: 'var(--text-10)',
          lineHeight: '16.8px',
        },
      },
    },
  }),
  variants: {
    [TemplateName.pdpv6]: () => ({
      addToBagButtonWrapper: {
        marginTop: '0',
      },
    }),
    [TemplateName.pdpv7]: () => ({
      headerTitle: {
        textAlign: 'center',
        fontSize: 'var(--text-44)',
        width: '100%',
        marginLeft: 0,
        marginRight: 0,
        marginBottom: 'var(--spacing-6)',
      },
      addToBagButtonWrapper: {
        marginTop: '0',
      },
    }),
  },
}
