export default {
  baseStyle: ({ theme }) => ({
    wrapper: {
      py: 'var(--spacing-8)',
      width: '100%',
      maxWidth: '1440px',
      margin: '0 auto',
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        py: 'var(--spacing-6)',
      },
    },
    title: {
      ...theme.typography['text-display4-xl'],
      textAlign: 'center',
      marginBottom: 'var(--spacing-6)',
      px: 'var(--spacing-6)',
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        ...theme.typography['text-display4-s'],
        px: '22px',
      },
    },
    tabsWrapper: {
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'column',
      width: '100%',
      px: 'var(--spacing-6)',
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        marginBottom: 'var(--spacing-6)',
        px: '22px',
      },
    },
    tabList: {
      bg: 'var(--color-white-base)',
      borderRadius: 'var(--border-radius-full)',
      p: 'var(--spacing-2)',
      gap: '20px',
      boxShadow: '0px 4.846px 13.933px 0px rgba(191,191,191,0.25)',
      border: 'var(--border-width-s) solid var(--color-white-base)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'start',
      height: '63px',
      width: 'fit-content',
      marginBottom: 'var(--spacing-6)',
      [`@media (min-width: ${theme.breakpoints.md})`]: {
        '&:has(+ div:not(:empty))': {
          marginBottom: 'var(--spacing-8)',
        },
      },
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        gap: 'unset',
        width: '100%',
        height: '52px',
        padding: '6px',
      },
    },
    tabPanels: {
      '&:not(:empty)': {
        marginBottom: 'var(--spacing-6)',
      },
    },
    tabPanel: {
      padding: '0',
    },
    tab: {
      borderRadius: 'var(--border-radius-full)',
      fontFamily: 'var(--font-face1-normal)',
      fontSize: 'var(--text-16)',
      fontWeight: 'normal',
      letterSpacing: 'var(--letter-spacing-s)',
      lineHeight: 'var(--line-height-xl)',
      textAlign: 'center',
      whiteSpace: 'nowrap',
      pt: '14px',
      px: 'var(--spacing-3)',
      pb: 'var(--spacing-3)',
      height: '48px',
      minWidth: '103px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'all 0.2s ease-in-out',
      color: 'var(--color-primary, #000003)',
      bg: 'transparent',
      border: 'none',
      _hover: {
        bg: 'var(--color-black-10)',
        color: 'var(--color-primary, #000003)',
        borderColor: 'var(--color-black-10)',
      },
      _selected: {
        bg: 'var(--color-black-base)',
        color: 'var(--color-white-base)',
        borderColor: 'var(--color-black-base)',
        minWidth: '128px',
        px: '10px',
        _hover: {
          bg: 'var(--color-black-base)',
          color: 'var(--color-white-base)',
        },
        [`@media (max-width: ${theme.breakpoints.md})`]: {
          minWidth: 'unset',
        },
      },
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        fontSize: 'var(--text-14)',
        minWidth: 'unset',
        flex: '1',
        height: '40px',
        padding: '10px var(--spacing-3)',
      },
    },
    viewMoreContainer: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: 'var(--spacing-8)',
      marginBottom: 'var(--spacing-4)',
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        marginTop: 'l',
        marginBottom: 0,
      },
    },
    viewMoreButton: {
      display: 'flex',
      alignItems: 'center',
      gap: 'var(--spacing-3)',
      padding: 'var(--spacing-4) var(--spacing-8)',
      border: 'none',
      backgroundColor: 'transparent',
      color: 'var(--color-primary)',
      fontSize: 'var(--text-14)',
      lineHeight: '100%',
      fontWeight: 'var(--font-weight-medium)',
      letterSpacing: 'var(--letter-spacing-xs)',
      [`@media (max-width: ${theme.breakpoints.md})`]: {
        fontSize: 'var(--text-12)',
      },
    },
    viewMoreText: {
      fontSize: 'var(--text-14)',
      fontWeight: 'var(--font-weight-medium)',
      textTransform: 'uppercase',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
  }),
}
