export default {
  baseStyle: ({ theme }) => ({
    inlineSearchContainer: {
      backgroundColor: '#F0F0F0', // missing desing tokens
      width: '100%',
      p: 'var(--spacing-8) var(--spacing-3) 52px',
    },
    inlineSearchWraper: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      backgroundColor: 'var(--color-white-base)',
      borderRadius: 'var(--border-radius-xl)',
      position: 'relative',
      alignItems: 'center',
      p: '0',
    },
    blueStar: {
      position: 'absolute',
      top: '63px',
      right: '19px',
    },
    redStar: {
      position: 'absolute',
      top: '20px',
      left: '18px',
    },
    searchTitle: {
      ...theme.typography['text-display4-s'],
      textAlign: 'center',
      fontWeight: '700',
      mt: '46px',
      zIndex: 1,
      p: '0 var(--spacing-6)',
    },
    suggestionsWrapper: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      gap: 'var(--spacing-2)',
      mt: 'var(--spacing-4)',
      mb: '18px',
    },
    suggestionsHeader: {
      ...theme.typography['text-body1-xs'],
      fontSize: 'var(--text-10)',
      p: '0 var(--spacing-6)',
    },
    suggestionsList: {
      gap: 'var(--spacing-1)',
      pr: 'var(--spacing-6)',
      display: 'flex',
      pl: 'var(--spacing-6)',
    },
    pill: {
      display: 'flex',
      p: 'var(--spacing-2) 14px',
      minHeight: '36px',
      borderRadius: '59px',
      border: '1px solid var(--color-neutral-light-2)',
      backgroundColor: 'var(--color-white-base)',
      gap: '6px',
      alignItems: 'center',
      fontFamily: 'var(--font-face1-extended-normal)',
      fontSize: 'var(--text-10)',
      lineHeight: 'var(--line-height-xxs)',
      letterSpacing: 'var(--letter-spacing-xs)',
    },
    suggestionsContainer: {
      width: '100%',
    },
    inputWrapper: {
      width: '100%',
      mt: '20px',
      position: 'relative',
      p: '0 var(--spacing-6)',
    },
    inputInnerWrapper: {
      position: 'relative',
      width: '100%',
      minHeight: '50px',
    },
    inputContainer: {
      position: 'absolute',
      zIndex: 12,
      width: '100%',
      minHeight: '50px',
      backgroundColor: 'var(--color-neutral-light)',
      borderRadius: 'var(--border-radius-full)',
      display: 'flex',
      alignItems: 'center',
    },
    inputRecommendationsWrapper: {
      position: 'absolute',
      zIndex: 11,
      width: '100%',
      backgroundColor: 'var(--color-white-base)',
      borderRadius: 'var(--border-radius-xl)',
      display: 'flex',
      boxShadow: '0px 6px 10px -3px rgba(0, 0, 0, 0.102)',
    },
    input: {
      fontSize: 'var(--text-16)',
      fontFamily: 'var(--font-face1-normal)',
      color: 'var(--color-primary)',
      pl: '50px',
      height: '24px',
      border: 0,

      '&:focus, &:focus-visible, *[data-focus]': {
        boxShadow: 'none',
        outline: 'none',
        borderColor: 'inherit',
      },
    },
    inputLeftElement: {
      p: '11px',
      top: '-7px',
      left: '5px',
    },
    inputRightElement: {
      fontSize: 'var(--text-16)',
      fontFamily: 'var(--font-face1-normal)',
      color: 'var(--color-primary)',
      textDecoration: 'underline',
      textTransform: 'capitalize',
      top: '-9px',
      right: '16px',
      '&.hide': {
        display: 'none',
      },
    },
    recommendationsList: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      mt: '50px',
      gap: '21px',
      p: '17px var(--spacing-4) var(--spacing-4)',
    },
    recomendationLink: {
      fontFamily: 'var(--font-face1-extended-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-12)',
      lineHeight: 'var(--line-height-l)',
      letterSpacing: 'var(--letter-spacing-xs)',
      color: 'var(--color-neutral-medium)',
    },
    recomendationLinkHighlight: {
      color: 'var(--color-black-base)',
    },
    placeHolderContainer: {
      position: 'absolute',
      height: '0px',
      width: '100%',
    },
    verticalSliderContainer: {
      height: '50px',
      overflow: 'hidden',
      position: 'relative',
      pointerEvents: 'none',
      left: '45px',
      top: '-12px',
    },
    verticalSlider: {
      position: 'absolute',
      top: '0',
      left: '0',
    },
    sliderItem: {
      whiteSpace: 'nowrap',
      fontFamily: 'var(--font-face1-extended-normal)',
      fontWeight: 400,
      fontSize: 'var(--text-12)',
      lineHeight: 'var(--line-height-l)',
      letterSpacing: 'var(--letter-spacing-xs)',
      color: 'var(--color-neutral-medium)',
      mt: '14px',
      opacity: '0',
      position: 'absolute',
      transform: 'translateY(-50px)',
      transition: 'transform 0.6s cubic-bezier(0.7, -0.4, 0.4, 1.4), opacity 0.6s ease-in-out',
      '&.active': {
        transform: 'translateY(3px)',
        opacity: '1',
      },
      '&.prev': {
        transform: 'translateY(-50px)',
        opacity: '0',
      },
      '&.next': {
        transform: 'translateY(50px)',
        opacity: '0',
      },
    },
  }),
}
